import { styles } from "../../styles/styles";

export default function Description() {
    return (
        <div>
            <div className={`${styles.container} flex flex-col gap-4`}>
                <h3 className="text-white font-bold text-[18px] leading-6.5 tracking-[0.12px]">Story Line</h3>
                <p className="text-[#9CA4AB] tracking-[0.5%] leading-6 text-[16px] font-medium">The Last of Us is an American <a className="underline" href="https://en.wikipedia.org/wiki/Apocalyptic_and_post-apocalyptic_fiction" target="_blank" rel="noopener noreferrer">apocalyptic and post-apocalyptic fiction</a> <a className="underline" href="https://en.wikipedia.org/wiki/Drama_(film_and_television)" target="_blank" rel="noopener noreferrer">drama</a> television series created by <a className="underline" href="https://en.wikipedia.org/wiki/Craig_Mazin" target="_blank" rel="noopener noreferrer">Craig Mazin</a> and <a className="underline" href="https://en.wikipedia.org/wiki/Neil_Druckmann" target="_blank" rel="noopener noreferrer">Neil Druckmann</a> for <a className="underline" href="https://en.wikipedia.org/wiki/HBO" target="_blank" rel="noopener noreferrer">HBO</a>. Based on <a className="underline" href="https://en.wikipedia.org/wiki/The_Last_of_Us" target="_blank" rel="noopener noreferrer">the video game</a> developed by <a className="underline" href="https://en.wikipedia.org/wiki/Naughty_Media" target="_blank" rel="noopener noreferrer">Naughty Dog</a>, the series is set in 2023, twenty years into a <a className="underline" href="https://en.wikipedia.org/wiki/2023_pandemic" target="_blank" rel="noopener noreferrer">pandemic</a> caused by a mass <a className="underline" href="https://en.wikipedia.org/wiki/Fungal_infection" target="_blank" rel="noopener noreferrer">fungal infection</a>, which causes its hosts to transform into <a className="underline" href="https://en.wikipedia.org/wiki/Zombie" target="_blank" rel="noopener noreferrer">zombie</a>-like creatures and <a className="underline" href="https://en.wikipedia.org/wiki/Collapse" target="_blank" rel="noopener noreferrer">collapses society</a>. The series follows <a className="underline" href="https://en.wikipedia.org/wiki/Joel_(The_Last_of_Us)" target="_blank" rel="noopener noreferrer">Joel</a> (<a className="underline" href="https://en.wikipedia.org/wiki/Pedro_Pascal" target="_blank" rel="noopener noreferrer">Pedro Pascal</a>), a smuggler tasked with escorting the immune teenager <a className="underline" href="https://en.wikipedia.org/wiki/Ellie_(The_Last_of_Us)" target="_blank" rel="noopener noreferrer">Ellie</a> (<a className="underline" href="https://en.wikipedia.org/wiki/Bella_Ramsey" target="_blank" rel="noopener noreferrer">Bella Ramsey</a>) across a post-apocalyptic United States.... <span className="text-[#00925D]">More</span></p>
            </div>
        </div>
    )
}